//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnimalAppointment()
        {
            this.AppointmentMedicines = new HashSet<AppointmentMedicine>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual AppointmentType AppointmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentMedicine> AppointmentMedicines { get; set; }
    }
}
