//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public string Breed { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public int StatusId { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int Age { get; set; }
        public int GenderId { get; set; }
        public string Color { get; set; }
        public string CapturePlace { get; set; }
        public string Sign { get; set; }
        public int CuratorId { get; set; }
        public byte[] Image { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalAppointment> AnimalAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalComment> AnimalComments { get; set; }
    }
}
