//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.AnimalAppointments = new HashSet<AnimalAppointment>();
            this.AnimalComments = new HashSet<AnimalComment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Breed { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string Color { get; set; }
        public string Character { get; set; }
        public string CapturePlace { get; set; }
        public string Sign { get; set; }
        public Nullable<int> CuratorId { get; set; }
        public byte[] Image { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalAppointment> AnimalAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalComment> AnimalComments { get; set; }
    }
}
