//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentMedicine
    {
        public int Id { get; set; }
        public Nullable<int> AppintmentId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AnimalAppointment AnimalAppointment { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
