//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentMedicine
    {
        public int Id { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AnimalAppointment AnimalAppointment { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
